
version: 2
jobs:
  build:
    working_directory: ~/CalculateYourAverage
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}-{{ checksum  "domain/build.gradle" }}-{{ checksum  "data/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key:  jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}-{{ checksum  "domain/build.gradle" }}
                         -{{ checksum  "data/build.gradle" }}
      - run:
          name: Run App Module Unit Tests
          command: ./gradlew :app
      - store_artifacts:
          path: app/build/reports
      - run:
          name: Run Domain Module Unit Tests
          command: ./gradlew :domain
      - store_artifacts:
          path: domain/build/reports
      - store_test_results:
          path: domain/build/test-results
      - run:
          name: Run Data Module Unit Tests
          command: ./gradlew :data
      - store_artifacts:
          path: data/build/reports
      - store_test_results:
          path: data/build/test-results
      - run:
          name: Run Lint Test
          command: ./gradlew lint
      - store_artifacts:
          path: app/build/reports